options:
  # De standaard styleguide regels worden niet gebruikt
  merge-default-rules: false
files:
  # De bestanden die gebruikt kunnen worden zijn: css, sass en scss
  include: '**/*.s+(a|c)ss'
# Alles wat onder de rules staat en een cijfer hebben van 1 of 2 zijn actief. Alles met een 0 is uitgeschakeld.
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-debug: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-trailing-zero: 0

  # Name Formats
  function-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 
    - 1
    -
      convention: hyphenatedbem
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false

  # Style Guide
  border-zero: 1
  brace-style: 
    - 1
    -
      style: '1tbs'
    - allow-single-line: true
  empty-args: 0
  hex-length: 
    - 1
    -
      style: long
  hex-notation: 1
  indentation: 
    - 1
    - 
      size: 4
  leading-zero: 0
  nesting-depth: 0
  quotes: 
    - 1
    -
      style: single
  shorthand-values: 1
  url-quotes: 1
  zero-unit: 0

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 0
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 1
  final-newline: 1